name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # Trigger this workflow when you push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2
        
      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        
      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Use the OpenAI API Key from GitHub Secrets
      - name: Run Streamlit with OpenAI API Key
        run: |
          streamlit run your_streamlit_app.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Access the secret here
